### ISSUE TITLE
Metal Gear Solid - broken main menu

### ISSUE THREAD

**Issue by WinterSnowfall** [WinterSnowfall/d7vk#16]
The game works, however performance is very poor.

Certain sections of the main menu also lack proper texturing and text display.

**Comment by WinterSnowfall** [comment]
Incredibly, also fixed in https://github.com/WinterSnowfall/d7vk/commit/2b2d68d327979114ab3ef9d4d713219b5b6a5b03.

**Comment by billbeans** [comment]
This game works for me when enabling D7VK on the latest GE=Proton, but the FMVs still don't render. I'm playing the original PC version, and they appear to be .ddv files in the 'movie' folder. Is there any way to make these render? I don't understand why they can't work.

**Comment by WinterSnowfall** [comment]
> This game works for me when enabling D7VK on the latest GE=Proton, but the FMVs still don't render.

We don't have control over media/video playback and decoding, that's typically relegated to DDraw itself and other Wine components. If it doesn't work with WineD3D, it won't work with D7VK, I'm afraid.

I'm sure they *can* work if proper fixes are done in Wine, but it's not a D3D problem you're currently hitting.

P.S.: If you're talking about pre-mission sequences though, they seem to work just fine here (I'm on Wine Staging, not Proton):

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/568269b9-38a5-416b-a335-8b781552d21f" />

**Comment by billbeans** [comment]
Yeah, the pre-mission sequences and most cutscenes in the game work, but there are real-life footage cutscenes occasionally in the game that fail to render, even on modern Windows. A quick way to see what I mean is to start up the VR Missions disc and watch the opening cutscene fail to render, although if you're playing the GOG version it should work. I'm trying to play from an original CD.

**Comment by WinterSnowfall** [comment]
> A quick way to see what I mean is to start up the VR Missions disc and watch the opening cutscene fail to render.

Understood. But yeah, we have no say in that *at all*.

The GOG version indeed seems to work around it somehow:

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/57dab1fb-9bb1-4765-b4f5-0ffb0156beaf" />

**Comment by billbeans** [comment]
So it would need to be some kind of other ddraw compatibility layer to make them show up? I just tried placing the GOG executables in my game dir, and the FMVs do show but they are extremely choppy/laggy, which is expected for the video, but the audio is too. I can't believe they wouldn't try converting them to a more common format for the re-release, unless the exe wouldn't know to play them.

**Comment by WinterSnowfall** [comment]
> So it would need to be some kind of other ddraw compatibility layer to make them show up?

No, I'm afraid this has more to do with the game's own internal libraries than anything else. I'm not too familiar with the issue, since it's outside of D3D, but it could very well be the original video format is very obscure, and thus poorly supported on modern Windows & Wine.
